<program> ::= <statement>*

<statement> ::= <assignment> | <function_call>

<assignment> ::= <implied_assignment>
               | <full_assignment>
               | <value_assignment>
               | <type_assignment>

<full_assignment> ::= (<type_assignment> | <identifier>) (":" | "=") <expression>
<implied_assignment> ::= <identifier> ("::" | ":=") <expression>
<value_assignment> ::= <identifier> "=" <value>
<type_assignment> ::= <identifier> ":" <type>

<special_identifier> ::= "#" <identifier>
<identifier> ::= ([a-z] | [A-Z] | "_") ([a-z] | [A-Z] | [0-9] | "_")*

<expression> ::= <type>
               | <value>
               | <function_definition>
               | <code_block>

<type> ::= <type_function_call>
         | <function_type>
         | <identifier>
         | <literal>

<value> ::= <identifier>
          | <literal>
          | <binary_expression>
          | <unary_expression>
          | <function_call>

<function_definition> ::= <function_type> <code_block>

<function_type> ::= "(" (<type_assignment> ("," <type_assignment>)*)? ")"
                    ("->" ((<type_assignment> | <type>) ("," <type_assignment> | <type>)*)?)

<code_block> ::= "{" <program> "}"

<function_call> ::= (<special_identifier> | <identifier>) "(" (<function_argument> ("," <function_argument>)*)? ")"
<function_argument> ::= (<identifier> ":")? <value>
<type_function_call> ::= <identifier> "(" (<type_function_argument> ("," <type_function_argument>)*)? ")"
<type_function_argument> ::= (<identifier> ":")? <type>

<binary_expression> ::= <value> <binary_operator> <value>
<binary_operator> ::= "+" | "-" | "*" | "/" | "==" | "!=" | "<" | ">" | "<=" | ">=" | "||" | "&&"

<unary_expression> ::= <unary_operator> <value>
<unary_operator> ::= "!" | "-"

<literal> ::= <integer> | <string> | <boolean>
<integer> ::= [0-9]+
<string> ::= "\"" "\""
<boolean> ::= "true" | "false"
